name: test

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        description: The environment to generate plan for
        required: true

jobs:
  build:

    runs-on: ubuntu-22.04-2core-8ram-75ssd
    environment:
      name: ${{ inputs.target-env }}

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        echo "${{ env.NAME }}"
