name: test

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        description: The environment to generate plan for
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        echo "${{ vars.NAME }}"
